import esbuild from "esbuild";
import builtins from "builtin-modules";
import { copyFile, mkdir } from "node:fs/promises";

const outdir = ".obsidian/plugins/text-file-editor";
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/`;

await mkdir(outdir, { recursive: true });

await esbuild.build({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    ...builtins
  ],
  format: "cjs",
  logLevel: "info",
  minify: false,
  outfile: `${outdir}/main.js`,
  platform: "browser",
  sourcemap: "inline",
  target: "es2020"
});

await copyFile("manifest.json", `${outdir}/manifest.json`);
await copyFile("styles.css", `${outdir}/styles.css`);
